services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    env_file: .env


  db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5
